enum ResultStatus {
    SUCCESS = 200,
    NOTE_ACCESS_CODE_EXCEPTION = 211,
    EXCEPTION = 400,
    ERROR = 500,
    USER_SERVICE_EXCEPTION = 600,
    USER_TOKEN_EXCEPTION = 601,
    NOTE_SERVICE_EXCEPTION = 700,
    ADMIN_SERVICE_EXCEPTION = 800,
    ADMIN_TOKEN_EXCEPTION = 801,
}
export default ResultStatus;
